export { ReactComponent as CalendarAltOIcon } from './calendar-alt-o.svg'
export { ReactComponent as CheckedCircleIcon } from './checked-circle.svg'
export { ReactComponent as DefaultAvatarIcon } from './default-avatar.svg'
export { ReactComponent as ExclamationCircleIcon } from './exclamation-circle.svg'
export { ReactComponent as PlayCircle, ReactComponent as PlayCircleIcon } from './play-circle.svg'
export { ReactComponent as PlayFill } from './play-fill.svg'
export { ReactComponent as TextIcon } from './text.svg'
export { ReactComponent as UserOIcon } from './user-o.svg'
